<a href="https://colab.research.google.com/github/vaguiar/capstone-project-2019/blob/vin-data-exp/Nemsis_V3_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nemsis V3 Data Exploration

## Load Data from Drive

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd
import numpy as np

## Uncomment this to read data from Drive

# nemsis_v3_link = '/content/drive/My Drive/Capstone Project 2019/data/data_20190929.csv'
# v3_data = pd.read_csv(nemsis_v3_link)

In [58]:
v3_data.head(5)

  Primary Impression ICD Name  ... Count of Events
0    Opioid related disorders  ...               1
1    Opioid related disorders  ...               1
2    Opioid related disorders  ...               1
3    Opioid related disorders  ...               1
4    Opioid related disorders  ...               1

[5 rows x 24 columns]

## Understanding the data
Fields, values, ranges etc

In [59]:
# Columns in the data
cols = v3_data.columns
cols

Index(['Primary Impression ICD Name', 'Primary Impression ICD 10', 'Race',
       'Patient Age', 'Gender', 'US Census Regions', 'US Census Divisions',
       'NHTSA Regions', 'NASEMSO Regions', 'Urbanicity', 'Population Density ',
       'Minority ', 'Hispanic ', 'Poverty ', 'Uninsured ', 'Disabled ',
       'Education ', 'Year ', 'Month of Year', 'Day of Month',
       'Hour of the Day', 'Event Datetime', 'Event Date', 'Count of Events'],
      dtype='object')

In [60]:
# dtypes of the columns
v3_data.dtypes

Primary Impression ICD Name    object
Primary Impression ICD 10      object
Race                           object
Patient Age                    object
Gender                         object
US Census Regions              object
US Census Divisions            object
NHTSA Regions                  object
NASEMSO Regions                object
Urbanicity                     object
Population Density             object
Minority                       object
Hispanic                       object
Poverty                        object
Uninsured                      object
Disabled                       object
Education                      object
Year                            int64
Month of Year                   int64
Day of Month                    int64
Hour of the Day                object
Event Datetime                 object
Event Date                     object
Count of Events                 int64
dtype: object

### Stats of the cols which are of types=np.object i.e. exclude int64 cols. Some to note are stats about unique values, top values etc

In [61]:
stats = v3_data.describe(percentiles=[], include=np.object)
stats

       Primary Impression ICD Name  ...  Event Date
count                       271833  ...      271833
unique                          85  ...         991
top                Suicide attempt  ...  2018/11/01
freq                        103534  ...         487

[4 rows x 20 columns]

### Looking at only those columns that have <15 unique values, to get a sense of what those values are

In [62]:
uniq = pd.DataFrame()

for col in stats.columns:
  if stats.loc['unique'][col] <= 15:
    # print(pd.unique(v3_data[col]))
    uniq = uniq.append(pd.Series(data=pd.unique(v3_data[col]),name=col))

uniq

                                                   0   ...       14
Race                 American Indian or Alaska Native  ...      NaN
Patient Age                                     41-50  ...  101-110
Gender                                           Male  ...      NaN
US Census Regions                             Midwest  ...      NaN
US Census Divisions                West North Central  ...      NaN
NHTSA Regions                                Region 5  ...      NaN
NASEMSO Regions                    Great Lakes Region  ...      NaN
Urbanicity                                      Urban  ...      NaN
Population Density                             >=1000  ...      NaN
Minority                                        >=51%  ...      NaN
Hispanic                                       6%-25%  ...      NaN
Poverty                                         >=26%  ...      NaN
Uninsured                                     16%-20%  ...      NaN
Disabled                                      11%-20%  ...      NaN
Education                                     76%-80%  ...      NaN

[15 rows x 15 columns]